# Generated by Django 3.1 on 2020-11-26 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Title', models.TextField(blank=True)),
                ('Text', models.TextField(blank=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_won_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
