# Generated by Django 3.1 on 2020-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barter', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
