# Generated by Django 3.1 on 2020-11-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barter', '0004_auto_20201126_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Winner',
            new_name='winner',
        ),
    ]
