# Generated by Django 3.1 on 2020-11-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barter', '0005_auto_20201127_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
