# Generated by Django 3.1 on 2020-11-28 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barter', '0006_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_won_posts', to='Barter.user'),
        ),
    ]
