# Generated by Django 3.1 on 2020-12-08 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barter', '0009_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('barter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='barter_messages', to='Barter.post')),
                ('reciver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recived_message', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
