# Generated by Django 3.1 on 2020-12-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barter', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='rejected',
            field=models.BooleanField(null=True),
        ),
    ]
