# Generated by Django 3.1 on 2020-12-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barter', '0013_auto_20201210_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
    ]
